my_shop/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from api import views as api_view

router_v1 = SimpleRouter()
router_v1.register(
    "categories", api_view.CategoriesViewSet, basename="categories"
)
router_v1.register(
    "manufacturer", api_view.ManufacturerViewSet, basename="manufacturer"
)
router_v1.register(
    "cart", api_view.ShoppingCartViewSet, basename="shopping_cart"
)
router_v1.register(
    "order", api_view.OrderViewSet, basename="order"
)
router_v1.register(
    "products", api_view.ProductsViewSet, basename="products"
)
router_v1.register(
    r"products/(?P<product_id>\d+)/reviews",
    api_view.ReviewViewSet,
    basename="review",
)

urlpatterns = [
    path(
        "auth/email_verification/",
        api_view.email_send_confirmation_code,
        name="email_send_confirmation_code",
    ),
    path("auth/sign_up/", api_view.user_signup, name="user_signup"),
    path("auth/token/", api_view.get_token, name="user_get_token"),
    path("", include(router_v1.urls)),
]

my_shop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="index"),
    path(
        "product/<int:product_id>/",
        views.product_detail_view,
        name="product_detail",
    ),
    path(
        "product/<int:product_id>/edit_review/<int:review_id>/",
        views.product_detail_view,
        name="edit_review",
    ),
    path(
        "product/<int:product_id>/add_review/",
        views.add_review,
        name="add_review",
    ),
    path(
        "delete_review/<int:review_id>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "category/<slug:category_slug>/",
        views.CategoryListView.as_view(),
        name="category",
    ),
    path(
        "manufacturer/<slug:manufacturer_slug>/",
        views.ManufacturerListView.as_view(),
        name="manufacturer",
    ),
]

my_shop/my_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from users.views import UserLoginView

handler404 = "pages.views.page_not_found"
handler500 = "pages.views.server_error"

schema_view = get_schema_view(
    openapi.Info(
        title="DIY shop API",
        default_version="v1",
        description="Документация для приложения DIY shop",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@diy_shop.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/login/", UserLoginView.as_view(), name="login"),
    path("auth/", include("django.contrib.auth.urls")),
    path("user/", include("users.urls")),
    path("pages/", include("pages.urls")),
    path("api/", include("api.urls")),
    path("card/", include("shopping_cart.urls")),
    path("order/", include("orders.urls")),
    path("", include("main.urls")),
]

urlpatterns += [
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# Подключаем дебаг-панель:
if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов
    # из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
# Подключаем функцию static() к urlpatterns:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/pages/urls.py
from django.urls import path

from pages import views

app_name = "pages"

urlpatterns = [path("about/", views.AboutView.as_view(), name="about")]

my_shop/shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = "cart"

urlpatterns = [
    path("cart/", views.show_cart, name="cart"),
    path("cart_add/", views.cart_add, name="cart_add"),
    path(
        "cart_change/<int:colorproduct_id>/",
        views.cart_change,
        name="cart_change",
    ),
    path(
        "cart_remove/<int:cart_id>",
        views.cart_remove,
        name="cart_remove",
    ),
]

my_shop/users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("profile_edit/", views.UserProfileView.as_view(), name="profile"),
    path(
        "registration/email_verification",
        views.email_verification,
        name="email_verification",
    ),
    path(
        "registration/code_verification",
        views.code_verification,
        name="code_verification",
    ),
    path(
        "registration/", views.UserRegistration.as_view(), name="registration"
    ),
]

my_shop/templates/includes/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ShoppingOnline 2024</p></div>
</footer>

my_shop/templates/includes/navigation.html
{% load django_bootstrap5 %}
{% load cart_tags %}

{% product_count request as product_count %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'main:index' %}">ShoppingOnline</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Главная</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'pages:about' %}">О компании</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Категории
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:index' %}">Все товары</a></li>
                        <li><hr class="dropdown-divider"></li>
                        {% for category in categories %}
                            <li><a class="dropdown-item" href="{% url 'main:category' category.slug %}">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Производители</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:index' %}">Все товары</a></li>
                        <li><hr class="dropdown-divider"></li>
                        {% for manufacturer in manufacturers %}
                            <li><a class="dropdown-item" href="{% url 'main:manufacturer' manufacturer.slug %}">{{ manufacturer }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <div class="d-flex align-items-center">
                {% if user.is_authenticated %}
                    <span class="navbar-text" style="margin-right: 20px;">Пользователь: <a href="{% url 'users:profile' %}"><b>{{ user.username }}</b></a></span>
                    <a href="{% url 'logout' %}" class="btn btn-outline-dark me-2">Выйти</a>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-dark me-2">Войти</a>
                    <a href="{% url 'users:email_verification' %}" class="btn btn-outline-dark me-2">Регистрация</a>
                {% endif %}
                <form class="d-flex" action='{% url "cart:cart" %}'>
                    <button class="btn btn-outline-dark" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Корзина
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{product_count}}</span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</nav>

my_shop/templates/includes/paginator.html
{% load main_tags %}

{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% change_params page=1 %}">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?{% change_params page=page_obj.previous_page_number %}">
            <<
          </a>
        </li>
      {% endif %}
      {% for page in page_obj.paginator.page_range %}
        {% if page_obj.number == page %}
          <li class="page-item active">
            <span class="page-link">{{ page }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% change_params page=page %}">
              {{ page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% change_params page=page_obj.next_page_number %}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?{% change_params page=page_obj.paginator.num_pages %}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

my_shop/templates/includes/product_card.html
{% load static %}
{% load rating_tags %}



<div class="col mb-5">
    <div class="card h-100">
        <!-- Sale badge-->
        {% if product.sale %}
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Скидка {{ product.sale }}%</div>
        {% endif %}
        <!-- Product image-->
        <a href="{% url "main:product_detail" product.id %}">
            <img class="card-img-top" 
                src="{% if product.image %}{{ product.image.url }}{% else %}https://dummyimage.com/450x300/dee2e6/6c757d.jpg{% endif %}"
                alt="{{ product.name }}">
        </a>
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">
                    <a href="{% url "main:product_detail" product.id %}" class="text-dark">{{ product.name }}</a>
                </h5>
                <div class="mb-2">
                    <span class="text-muted">Категория: </span>
                    <a href="{% url "main:category" product.category.slug %}" class="text-decoration-none">{{ product.category }}</a>
                </div>
                <div class="mb-2">
                    <span class="text-muted">Производитель: </span>
                    <a href="{% url "main:manufacturer" product.manufacturer.slug %}" class="text-decoration-none">{{ product.manufacturer }}</a>
                </div>
                <div class="mb-2">
                    Доступно в <strong>{{ product.num_shop }}</strong> магазинах
                </div>
                <div class="mb-2">
                    В наличии: <strong>{{ product.num_products }}</strong> шт.
                </div>
                {% if product.num_coloursets %}
                    <div class="mb-2">
                        Всего цветов: <strong>{{ product.num_coloursets }}</strong>
                    </div>
                {% endif %}
                <!-- Product reviews-->
                {% if product.rating > 0 %}
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        {% get_range product.rating as range %}
                        {% for _ in range %}
                            <i class="bi bi-star-fill"></i>
                        {% endfor %}
                    </div>
                {% endif %}
                <!-- Product price-->
                {% if product.id in products_in_carts %}
                <div class="text-center">
                    <p>Товар уже в корзине</p>

                </div>
                {% endif %}

            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="fw-bold fs-5 text-center">
                {% if product.sale %}
                    <span class="text-muted text-decoration-line-through">{{ product.price }} руб.</span>
                    <br>
                    {{ product.actual_price }} руб.
                {% else %}
                    {{ product.price }} руб.
                {% endif %}
            </div>
            
                <div class="text-center">
                    <a class="btn btn-outline-dark mt-auto" href="{% url 'main:product_detail' product.id %}">Смотреть</a>
                </div>
            

        </div>
    </div>
</div>