my_shop/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from api import views as api_view

router_v1 = SimpleRouter()
router_v1.register(
    "categories", api_view.CategoriesViewSet, basename="categories"
)
router_v1.register(
    "manufacturer", api_view.ManufacturerViewSet, basename="manufacturer"
)
router_v1.register(
    "cart", api_view.ShoppingCartViewSet, basename="shopping_cart"
)
router_v1.register(
    "order", api_view.OrderViewSet, basename="order"
)
router_v1.register(
    "products", api_view.ProductsViewSet, basename="products"
)
router_v1.register(
    r"products/(?P<product_id>\d+)/reviews",
    api_view.ReviewViewSet,
    basename="review",
)

urlpatterns = [
    path(
        "auth/email_verification/",
        api_view.email_send_confirmation_code,
        name="email_send_confirmation_code",
    ),
    path("auth/sign_up/", api_view.user_signup, name="user_signup"),
    path("auth/token/", api_view.get_token, name="user_get_token"),
    path("", include(router_v1.urls)),
]

my_shop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="index"),
    path(
        "product/<int:product_id>/",
        views.product_detail_view,
        name="product_detail",
    ),
    path(
        "product/<int:product_id>/edit_review/<int:review_id>/",
        views.product_detail_view,
        name="edit_review",
    ),
    path(
        "product/<int:product_id>/add_review/",
        views.add_review,
        name="add_review",
    ),
    path(
        "delete_review/<int:review_id>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "category/<slug:category_slug>/",
        views.CategoryListView.as_view(),
        name="category",
    ),
    path(
        "manufacturer/<slug:manufacturer_slug>/",
        views.ManufacturerListView.as_view(),
        name="manufacturer",
    ),
]

my_shop/my_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from users.views import UserLoginView

handler404 = "pages.views.page_not_found"
handler500 = "pages.views.server_error"

schema_view = get_schema_view(
    openapi.Info(
        title="DIY shop API",
        default_version="v1",
        description="Документация для приложения DIY shop",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@diy_shop.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/login/", UserLoginView.as_view(), name="login"),
    path("auth/", include("django.contrib.auth.urls")),
    path("user/", include("users.urls")),
    path("pages/", include("pages.urls")),
    path("api/", include("api.urls")),
    path("card/", include("shopping_cart.urls")),
    path("order/", include("orders.urls")),
    path("", include("main.urls")),
]

urlpatterns += [
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# Подключаем дебаг-панель:
if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов
    # из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
# Подключаем функцию static() к urlpatterns:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/orders/urls.py
from django.urls import path

from orders import views

app_name = "order"

urlpatterns = [
    path("create-order/", views.create_order, name="create_order"),
]

my_shop/shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = "cart"

urlpatterns = [
    path("cart/", views.show_cart, name="cart"),
    path("cart_add/", views.cart_add, name="cart_add"),
    path(
        "cart_change/<int:colorproduct_id>/",
        views.cart_change,
        name="cart_change",
    ),
    path(
        "cart_remove/<int:cart_id>",
        views.cart_remove,
        name="cart_remove",
    ),
]

my_shop/users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("profile_edit/", views.UserProfileView.as_view(), name="profile"),
    path(
        "registration/email_verification",
        views.email_verification,
        name="email_verification",
    ),
    path(
        "registration/code_verification",
        views.code_verification,
        name="code_verification",
    ),
    path(
        "registration/", views.UserRegistration.as_view(), name="registration"
    ),
]

my_shop/shopping_cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models import ColorProduct, Product

User = get_user_model()


class CartQueryset(models.QuerySet):
    """Переопределяем QuerySet для ShoppingCart."""

    def total_price(self):
        """Метод для расчета общей стоимости корзины."""
        return sum(cart.product_price() for cart in self)

    def total_quantity(self):
        """Метод для расчета суммарного количества товаров в корзине."""
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class ShoppingCart(models.Model):
    """Модель корзины товаров."""

    # Делаем поле user необязательным, чтобы корзиной могли пользоваться
    # неаторизованные пользователи
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    product = models.ForeignKey(
        Product, verbose_name="Товар", on_delete=models.CASCADE
    )
    colorproduct = models.ForeignKey(
        ColorProduct, verbose_name="Товар цвета", on_delete=models.CASCADE
    )
    quantity = models.PositiveSmallIntegerField(verbose_name="Количество")
    # Добавляем поле чтобы session_key для неавторизованных пользователей
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата добавления"
    )

    objects = CartQueryset().as_manager()

    class Meta:
        verbose_name = "корзина"
        verbose_name_plural = "Корзины"
        default_related_name = "shoppingcart"
        unique_together = ("user", "colorproduct")

    def __str__(self) -> str:
        return f"Корзина {self.user.username} | Товар {self.product}"

    def product_price(self):
        """Метод для возврата стоимости одной позиции в корзине."""
        return round(self.product.actual_price * self.quantity, 2)

my_shop/shopping_cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    """Форма для добавления товара в корзину."""

    colorproduct_id = forms.IntegerField()

my_shop/shopping_cart/views.py
from django.shortcuts import get_object_or_404, redirect, render

from main.models import ColorProduct
from shopping_cart.forms import CartAddForm
from shopping_cart.models import ShoppingCart


def show_cart(request):
    """Отображение товаров в корзине."""

    if request.user.is_authenticated:
        shopping_carts = ShoppingCart.objects.filter(
            user=request.user
        ).select_related("colorproduct", "colorproduct__color", "product")
    else:
        shopping_carts = (
            ShoppingCart.objects.exclude(session_key=None)
            .filter(session_key=request.session.session_key)
            .select_related("colorproduct", "colorproduct__color", "product")
        )
    context = {"carts": shopping_carts}

    return render(request, "shopping_cart/cart.html", context=context)


def cart_add(request):
    """Добавление товаров в корзину."""

    form = CartAddForm(
        request.POST or None,
    )
    if form.is_valid():
        colorproduct_id = form.cleaned_data["colorproduct_id"]
        colorproduct = get_object_or_404(ColorProduct, id=colorproduct_id)

        if request.user.is_authenticated:
            cart = ShoppingCart.objects.filter(
                user=request.user,
                colorproduct=colorproduct,
            )
        else:
            # Добавляем неавторизированному пользователю
            # сессионный ключ, если его нет
            if not request.session.session_key:
                request.session.create()

            cart = ShoppingCart.objects.filter(
                session_key=request.session.session_key,
                colorproduct=colorproduct,
            )
        if cart.exists():
            cart = cart.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            if request.user.is_authenticated:
                ShoppingCart.objects.create(
                    user=request.user,
                    colorproduct=colorproduct,
                    product=colorproduct.product,
                    quantity=1,
                )
            else:
                ShoppingCart.objects.create(
                    session_key=request.session.session_key,
                    colorproduct=colorproduct,
                    product=colorproduct.product,
                    quantity=1,
                )
    return redirect(request.META["HTTP_REFERER"])


def cart_change(request, colorproduct_id):
    """Изменение корзины."""

    colorproduct = get_object_or_404(ColorProduct, id=colorproduct_id)

    if request.user.is_authenticated:
        cart = ShoppingCart.objects.filter(
            user=request.user, colorproduct=colorproduct
        )
    else:
        cart = ShoppingCart.objects.filter(
            session_key=request.session.session_key,
            colorproduct=colorproduct,
        )

    if cart.exists():
        cart = cart.first()
        if cart:
            cart.quantity -= 1
            # Если количество товара в корзине становится равным 0,
            # то удаляем этот товар из корзины
            if cart.quantity == 0:
                cart_remove(request, cart.id)
                return redirect(request.META["HTTP_REFERER"])
            cart.save()

    return redirect(request.META["HTTP_REFERER"])


def cart_remove(request, cart_id):
    """Удаление позиций из корзины."""

    cart = get_object_or_404(ShoppingCart, id=cart_id)
    cart.delete()
    return redirect(request.META["HTTP_REFERER"])

my_shop/templates/shopping_cart/cart.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block title %}Корзина{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Корзина</li>
{% endblock breadcrumb %}

{% block content %}
<style>
    .btn-compact {
        padding: 0.25rem 0.5rem;
        border: none;
        line-height: 1;
        vertical-align: middle;
    }
</style>
<section class="py-4">
    <div class="container">
        <h2>Ваша корзина</h2>
        {% if carts.total_quantity > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Товар</th>
                        <th>Цвет</th>
                        <th>Количество</th>
                        <th>Цена за единицу</th>
                        <th>Цена со скидкой</th>
                        <th>Сумма</th>
                        <th>Экономия</th>
                        <th></th> <!-- Колонка для удаления товара -->
                    </tr>
                </thead>
                <tbody>
                    {% for cart in carts %}
                        <tr>
                            <td><a href="{% url "main:product_detail" cart.product.id %}">{{ cart.product.name }}</a></td>
                            <td>{{ cart.colorproduct }}</td>
                            <td>
                                <a href="{% url 'cart:cart_change' cart.colorproduct.id %}" class="btn btn-sm btn-compact btn-outline-secondary">-</a>
                                {{ cart.quantity }}
                                <form action="{% url 'cart:cart_add' %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="colorproduct_id" value="{{ cart.colorproduct.id }}">
                                    <button type="submit" class="btn btn-sm btn-compact btn-outline-secondary">+</button>
                                </form>
                            </td>
                            <td>{{ cart.product.price }}</td>
                            <td>{{ cart.product.actual_price }}</td>
                            <td>{{ cart.product_price }}</td>
                            <td>{{ cart|total_saving }}</td>
                            <td>
                                <a href="{% url 'cart:cart_remove' cart.id %}" class="btn btn-danger btn-sm">Удалить</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">Общая сумма:</td>
                        <td>{{ carts.total_price }}</td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>



            {% if request.user.is_authenticated %}
            <div class="text-end">
                <a href="{% url "order:create_order" %}" class="btn btn-primary">Оформить заказ</a>
            </div>
            {% else %}
                <h4> Для оформления заказа, пожалуйста, зарегистрируйтесь:</h4>
                <a href="{% url 'users:email_verification' %}" class="btn btn-primary">Зарегистрироваться</a>
            {% endif %}
            {% else %}
            <p>Ваша корзина пуста.</p>
        {% endif %}
    </div>
</section>
{% endblock content %}