my_shop/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from api import views as api_view

router_v1 = SimpleRouter()
router_v1.register(
    "categories", api_view.CategoriesViewSet, basename="categories"
)
router_v1.register(
    "manufacturer", api_view.ManufacturerViewSet, basename="manufacturer"
)
router_v1.register(
    "cart", api_view.ShoppingCartViewSet, basename="shopping_cart"
)
router_v1.register(
    "order", api_view.OrderViewSet, basename="order"
)
router_v1.register(
    "products", api_view.ProductsViewSet, basename="products"
)
router_v1.register(
    r"products/(?P<product_id>\d+)/reviews",
    api_view.ReviewViewSet,
    basename="review",
)

urlpatterns = [
    path(
        "auth/email_verification/",
        api_view.email_send_confirmation_code,
        name="email_send_confirmation_code",
    ),
    path("auth/sign_up/", api_view.user_signup, name="user_signup"),
    path("auth/token/", api_view.get_token, name="user_get_token"),
    path("", include(router_v1.urls)),
]

my_shop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="index"),
    path(
        "product/<int:product_id>/",
        views.product_detail_view,
        name="product_detail",
    ),
    path(
        "product/<int:product_id>/edit_review/<int:review_id>/",
        views.product_detail_view,
        name="edit_review",
    ),
    path(
        "product/<int:product_id>/add_review/",
        views.add_review,
        name="add_review",
    ),
    path(
        "delete_review/<int:review_id>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "category/<slug:category_slug>/",
        views.CategoryListView.as_view(),
        name="category",
    ),
    path(
        "manufacturer/<slug:manufacturer_slug>/",
        views.ManufacturerListView.as_view(),
        name="manufacturer",
    ),
]

my_shop/my_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from users.views import UserLoginView

handler404 = "pages.views.page_not_found"
handler500 = "pages.views.server_error"

schema_view = get_schema_view(
    openapi.Info(
        title="DIY shop API",
        default_version="v1",
        description="Документация для приложения DIY shop",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@diy_shop.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/login/", UserLoginView.as_view(), name="login"),
    path("auth/", include("django.contrib.auth.urls")),
    path("user/", include("users.urls")),
    path("pages/", include("pages.urls")),
    path("api/", include("api.urls")),
    path("card/", include("shopping_cart.urls")),
    path("order/", include("orders.urls")),
    path("", include("main.urls")),
]

urlpatterns += [
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# Подключаем дебаг-панель:
if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов
    # из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
# Подключаем функцию static() к urlpatterns:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = "cart"

urlpatterns = [
    path("cart/", views.show_cart, name="cart"),
    path("cart_add/", views.cart_add, name="cart_add"),
    path(
        "cart_change/<int:colorproduct_id>/",
        views.cart_change,
        name="cart_change",
    ),
    path(
        "cart_remove/<int:cart_id>",
        views.cart_remove,
        name="cart_remove",
    ),
]

my_shop/main/models.py
from decimal import ROUND_UP, Decimal

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from main.choices import RATING_CHOICES

User = get_user_model()


class Shop(models.Model):
    """Модель магазина."""

    name = models.CharField(
        max_length=150, verbose_name="Название магазина", unique=True
    )
    address = models.TextField(
        max_length=300, verbose_name="Адрес магазина", unique=True
    )

    class Meta:
        verbose_name = "магазин"
        verbose_name_plural = "Магазины"
        default_related_name = "shop"
        unique_together = ("name", "address")
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    """Модель категория товаров."""

    name = models.CharField(
        max_length=50, verbose_name="Название категории", unique=True
    )
    description = models.TextField(
        max_length=450, verbose_name="Описание категории"
    )
    slug = models.SlugField(unique=True, verbose_name="Идентификатор")
    is_active = models.BooleanField(default=True, verbose_name="Опубликовано")

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "Категории"
        default_related_name = "category"
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Color(models.Model):
    """Модель цвета товара."""

    name = models.CharField(
        max_length=30, verbose_name="Название цвета", unique=True
    )

    class Meta:
        verbose_name = "цвет"
        verbose_name_plural = "Цвета"
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Country(models.Model):
    """Модель страны."""

    name = models.CharField(
        max_length=50, verbose_name="Название страны", unique=True
    )

    class Meta:
        verbose_name = "страна"
        verbose_name_plural = "Страны"
        default_related_name = "country"
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Manufacturer(models.Model):
    """Модель производителя."""

    name = models.CharField(
        max_length=50, verbose_name="Название производителя", unique=True
    )
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, verbose_name="Страна производителя"
    )
    slug = models.SlugField(unique=True, verbose_name="Идентификатор")
    is_active = models.BooleanField(default=True, verbose_name="Опубликовано")

    class Meta:
        verbose_name = "производитель"
        verbose_name_plural = "Производители"
        default_related_name = "manufacturer"
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    """Модель товара."""

    name = models.CharField(
        max_length=50, verbose_name="Название товара", unique=True
    )
    description = models.TextField(
        max_length=400, verbose_name="Описание товара"
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена"
    )
    sale = models.IntegerField(null=True, blank=True, verbose_name="Скидка")
    actual_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена со скидкой",
        validators=[MinValueValidator(Decimal("0.01"))],
    )
    is_active = models.BooleanField(default=True, verbose_name="Опубликовано")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Время добавления"
    )
    image = models.ImageField(
        "Изображение", upload_to="product_images", blank=True
    )
    category = models.ForeignKey(
        Category, verbose_name="Категрия", on_delete=models.CASCADE
    )
    manufacturer = models.ForeignKey(
        Manufacturer, verbose_name="Производитель", on_delete=models.CASCADE
    )
    color = models.ManyToManyField(
        Color,
        verbose_name="Цвета товара",
        through="ColorProduct",
    )

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "Товары"
        default_related_name = "product"
        ordering = ("created",)

    def __str__(self) -> str:
        return self.name

    @property
    def average_rating(self):
        reviews = self.reviews.all()
        if reviews:
            return reviews.aggregate(models.Avg("rating"))["rating__avg"]
        return 0

    def get_absolute_url(self):
        return reverse("main:product_detail", kwargs={"product_id": self.pk})

    def save(self, *args, **kwargs):
        if self.sale:
            discount_decimal = Decimal(self.sale) / Decimal(100)
            self.actual_price = self.price * (Decimal(1) - discount_decimal)
            self.actual_price = self.actual_price.quantize(
                Decimal(".01"), rounding=ROUND_UP
            )
        else:
            self.actual_price = self.price
        super().save(*args, **kwargs)


class ColorProduct(models.Model):
    """Модель для связи товаров и их цветов."""

    color = models.ForeignKey(
        Color, verbose_name="Цвет", on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product, verbose_name="Товар", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "цвет товара"
        verbose_name_plural = "Цвета товара"
        default_related_name = "colorproduct"
        unique_together = ("color", "product")

    def __str__(self):
        return self.color.name


class ColorProductShop(models.Model):
    """
    Модель для связи товаров определенных цветов
    с их наличиев в магазинах.
    """

    colorproduct = models.ForeignKey(
        ColorProduct, verbose_name="Цвет товара", on_delete=models.CASCADE
    )
    shop = models.ForeignKey(
        Shop, verbose_name="Магазин", on_delete=models.CASCADE
    )
    quantity = models.IntegerField(verbose_name="Количество")

    class Meta:
        verbose_name = "товар в магазине"
        verbose_name_plural = "Товары в магазине"
        default_related_name = "colorproductshop"
        unique_together = ("colorproduct", "shop")


class Review(models.Model):
    """Модель отзыва на товар."""

    text = models.TextField(max_length=1000, verbose_name="Текст отзыва")
    photo = models.FileField("Фото", blank=True, upload_to="photo", null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(
        verbose_name="Рейтинг", choices=RATING_CHOICES
    )
    product = models.ForeignKey(
        Product, verbose_name="Товар", on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, verbose_name="Автор", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "отзыв"
        verbose_name_plural = "Отзывы"
        default_related_name = "reviews"
        ordering = ("-created_at",)

my_shop/main/forms.py
from django import forms

from main.choices import RATING_CHOICES
from main.models import Review


class ReviewForm(forms.ModelForm):

    text = forms.CharField(
        label="Текст отзыва:",
        widget=forms.Textarea(
            attrs={"class": "form-control w-100", "rows": 3, "required": True}
        ),
    )
    rating = forms.ChoiceField(
        label="Поставьте оценку:",
        choices=RATING_CHOICES,
        widget=forms.Select(),
        required=True,
    )
    photo = forms.FileField(label="Добавьте фото:", required=False)

    class Meta:
        model = Review
        fields = ("text", "rating", "photo")


class PriceFilterForm(forms.Form):
    price_min = forms.IntegerField(
        label="Минимальная цена",
        required=False,
        widget=forms.NumberInput(attrs={"min": 0}),
    )
    price_max = forms.IntegerField(label="Максимальная цена", required=False)

my_shop/main/views.py
from collections import defaultdict

from django.conf import settings
from django.db.models import Avg, Count, Sum
from django.shortcuts import get_object_or_404, redirect, render

from main.forms import ReviewForm
from main.models import (Category, ColorProduct, ColorProductShop,
                         Manufacturer, Product, Review)
from main.views_mixins import BaseObjectListViewMixin, ObjectListViewMixin

paginate_by = getattr(settings, "PAGINATE_BY", 10)


class ProductListView(BaseObjectListViewMixin):
    """Отображение списка товаров"""


def product_detail_view(request, product_id, review_id=None):
    """Отображение страницы товара"""
    queryset = Product.objects.annotate(
        rating=Avg("reviews__rating"),
        reviews_count=Count("reviews"),
    ).select_related("category", "manufacturer", "manufacturer__country")
    product = get_object_or_404(queryset, id=product_id, is_active=True)

    # Добавляем в контекст данные о товаре в оффлайн магазинах
    grouped_data = defaultdict(list)
    for colorproductshop in (
        ColorProductShop.objects.filter(
            colorproduct__product=product, quantity__gt=0
        )
        .exclude(shop__name__icontains="Склад")
        .select_related("shop", "colorproduct", "colorproduct__color")
    ):
        grouped_data[colorproductshop.colorproduct].append(
            {
                "shop": colorproductshop.shop,
                "quantity": colorproductshop.quantity,
            }
        )

    shops_data = [
        {"colorproduct": color, "items": items}
        for color, items in grouped_data.items()
    ]

    # Добавляем в контекст данные о товаре в интернет магазине
    storage_data = (
        ColorProduct.objects.filter(
            product=product,
            colorproductshop__shop__name__icontains="Склад",
            colorproductshop__quantity__gt=0,
        )
        .select_related("color")
        .annotate(total=Sum("colorproductshop__quantity"))
    )

    # Добавляем список доступных цветов
    available_colors = list(set(
        list(storage_data)
        + [item["colorproduct"] for item in shops_data]
    ))

    # Добавляем выбранные пользователем цвета
    selected_colorproduct = request.GET.getlist("color")

    # Получаем все комментарии и их авторов
    reviews = product.reviews.select_related("user")

    # Проверяем, хочет ли пользователь отредактировать свой отзыв
    if review_id is not None:
        review_instance = get_object_or_404(Review, pk=review_id)
    else:
        review_instance = None

    # Создаем объект формы со всеми данными
    form = ReviewForm(
        request.POST or None,
        files=request.FILES or None,
        instance=review_instance,
    )
    if form.is_valid():
        review = form.save(commit=False)
        review.user = request.user
        review.product = product
        review.save()
        return redirect(product.get_absolute_url())

    # Сохраняем все полученные данные в контекст
    context = {
        "product": product,
        "shops_data": shops_data,
        "storage_data": storage_data,
        "available_colors": available_colors,
        "selected_colorproduct": selected_colorproduct,
        "form": form,
        "reviews": reviews,
    }
    return render(request, "main/product_detail.html", context)


def add_review(request, product_id):
    product = get_object_or_404(Product, id=product_id, is_active=True)
    form = ReviewForm(request.POST, files=request.FILES or None)
    if form.is_valid():
        review = form.save(commit=False)
        review.user = request.user
        review.product = product
        review.save()
    return redirect(product.get_absolute_url())


def delete_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    if review.user == request.user:
        review.delete()
    return redirect(review.product.get_absolute_url())


class CategoryListView(ObjectListViewMixin):
    related_model = Category
    slug_url_kwarg = "category_slug"


class ManufacturerListView(ObjectListViewMixin):
    related_model = Manufacturer
    slug_url_kwarg = "manufacturer_slug"

my_shop/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    Main Page
{% endblock title %}

{% block h1 %}
    {% if h1 %}
        {{ h1 }}
    {% else %}
        Магазин инструмента
    {% endif %}
{% endblock h1 %}

{% block description %}
    Делайте покупку с удовольствием
{% endblock description %}



{% block content %}
    
{% endblock content %}

my_shop/templates/main/product_detail.html
{% extends "base.html" %}
{% load rating_tags %}
{% load django_bootstrap5 %}
{% load cart_tags %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block breadcrumb %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Главная</a></li>
      <li class="breadcrumb-item"><a href="{% url 'main:category' product.category.slug %}">{{ product.category }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'main:manufacturer' product.manufacturer.slug %}">{{ product.manufacturer }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
    </ol>
  </nav>
{% endblock breadcrumb %}

{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <div class="position-relative">
                    {% if product.sale %}
                        <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem; z-index: 1000; border-radius: 0.5rem; padding: 0.5rem 1rem; font-size: 1rem; font-weight: bold;">
                          Скидка {{ product.sale }}%
                        </div>
                    {% endif %}
                    <a href="{% url 'main:product_detail' product.id %}">
                        <img class="card-img-top" 
                            src="{% if product.image %}{{ product.image.url }}{% else %}https://dummyimage.com/450x300/dee2e6/6c757d.jpg{% endif %}"
                            alt="{{ product.name }}"></a>
                    
                </div>
            </div>            
            <div class="col-md-8">
                <div class="card-body">
                    <h1 class="card-title">{{ product.name }}</h1>
                    <a href="{% url 'main:category' product.category.slug %}" class="badge bg-secondary">{{ product.category }}</a>
                    <p><strong>Производитель:</strong> <a href="{% url 'main:manufacturer' product.manufacturer.slug %}">{{ product.manufacturer }}</a></p>
                    <p><strong>Страна:</strong> {{ product.manufacturer.country }}</p>
                    <form id="colorFilterForm" method="GET">
                        <p><strong>Выберите цвет:</strong></p>
                        {% comment %} {% for item in shops_data %}
                            <label class="color-button {% if item.colorproduct.id|stringformat:'s' in selected_colorproduct %}selected{% endif %}">
                                <input type="radio" name="color" value="{{ item.colorproduct.id }}" onchange="submitForm()"
                                    {% if item.colorproduct.id|stringformat:'s' in selected_colorproduct %}checked{% endif %}
                                    style="display: none;">
                                {{ item.colorproduct }}
                            </label>
                        {% endfor %} {% endcomment %}

                        {% for item in available_colors %}
                            <label class="color-button {% if item.id|stringformat:'s' in selected_colorproduct %}selected{% endif %}">
                                <input type="radio" name="color" value="{{ item.id }}" onchange="submitForm()"
                                    {% if item.id|stringformat:'s' in selected_colorproduct %}checked{% endif %}
                                    style="display: none;">
                                {{ item }}
                            </label>
                        {% endfor %}
                    </form>

                    <style>
                        .color-button {
                            padding: 10px;
                            margin: 5px;
                            background-color: #f0f0f0;
                            border: 1px solid #dcdcdc;
                            display: inline-block;
                            cursor: pointer;
                        }
                        .color-button input[type="radio"] {
                            display: none;
                        }
                        .color-button.selected, .color-button:hover {
                            background-color: #007BFF;
                            color: white;
                        }
                    </style>

                    <div class="list-group list-group-flush">
                        <div class="list-group-item">
                            <strong>Цена:</strong> 
                            {% if product.sale %}
                                <span class="text-decoration-line-through text-muted" style="font-size: 1.2rem;">{{ product.price }} руб.</span>
                                <span class="text-danger fw-bold" style="font-size: 1.5rem;">{{ product.actual_price }} руб.</span>
                            {% else %}
                                <span class="fw-bold" style="font-size: 1.5rem;">{{ product.price }} руб.</span>
                            {% endif %}
                            
                        </div>
                        <div class="list-group-item">

                            
                            {% products_in_user_shopping_carts request as products_in_carts %}

                            {% if product.id  in products_in_carts %}
                                <p>Товар добавлен в корзину</p>
                            {% endif %}

                            <form action="{% url 'cart:cart_add' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="selected_colorproduct" name="colorproduct_id" value="">
                                <div>
                                    {% if product.id  in products_in_carts %}
                                        <button type="submit" class="btn btn-outline-dark mt-auto" id="addToCartButton" disabled>Добавить еще 1 товар в корзину</button>
                                    {% else %}
                                        <button type="submit" class="btn btn-outline-dark mt-auto" id="addToCartButton" disabled>Добавить в корзину</button>
                                    {% endif %}
                                </div>
                                    
                            </form>
                        </div>

                        
                        <div class="list-group-item">

                            {% if storage_data %}
                                <strong>Доступно в интернет-магазине:</strong>
                                <ul>                                    
                                    {% for item in storage_data %}
                                        <li>{{ item }} – {{item.total}} шт</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <strong>Недоступно для заказа в интернет-магизине</strong>
                            {% endif %}
                        </div>

                        <div class="list-group-item">
                            {% if shops_data %}
                            <strong>Доступно в оффлайн магазинах:</strong>
                            <ul>
                            {% for shop_data in shops_data %}
                                {% if selected_colorproduct %}
                                    {% if shop_data.colorproduct.id|stringformat:"s" in selected_colorproduct %}
                                        <li>{{ shop_data.colorproduct }}
                                            <ul>
                                                {% for item in shop_data.items %}
                                                    <li>{{ item.shop }} – {{ item.quantity }} шт</li>
                                                {% endfor %}
                                                
                                            </ul>
                                        </li>
                                    {% endif %}
                                {% else %}
                                    <li>{{ shop_data.colorproduct }}
                                        <ul>
                                            {% for item in shop_data.items %}
                                                <li>{{ item.shop }} – {{ item.quantity }} шт</li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                            {% else %}
                                <strong>Недоступно в оффлайн магазинах</strong>
                            {% endif %}
                        </div>

                        <div class="list-group-item">
                            <strong>Рейтинг:</strong> 
                            {% if product.rating == 0 %}
                                Неизвестен
                            {% else %}
                                {{ product.rating|floatformat:2 }}
                                <span class="d-flex align-items-center small text-warning">
                                    {% get_range product.average_rating as range %}
                                    {% for _ in range %}
                                        <i class="bi-star-fill"></i>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                        <div class="list-group-item"><strong>Количество оценок:</strong> {{ product.reviews_count }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <h2>Описание</h2>
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <p>{{ product.description }}</p>
        </div>
    </div>

    <!-- Форма и отзывы -->
    {% if user.is_authenticated %}
    <div class="card my-4">
        <div class="card-body">
            <h2 id="review_form"> 
                {% if '/edit_review/' in request.path %}
                    Отредактируйте отзыв:
                {% else %}
                    Оставьте свой отзыв:
                {% endif %}
            </h2>
            <form method="post" class="col-md-8" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary mt-2">
                    {% if '/edit_review/' in request.path %}
                    Изменить отзыв
                    {% else %}
                    Отправить отзыв
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
    {% endif %}

    <h2>Отзывы:</h2>
    {% for review in reviews %}
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <h5>{{ review.user }}</h5>
            <h6 class="text-muted">{{ review.created_at }}</h6>
            <div class="rating">
               {% get_range review.rating as review_range %}
               {% for star in review_range %}
                   <i class="bi-star-fill text-warning"></i>
               {% endfor %}
            </div>
            <p>{{ review.text }}</p>
            {% if review.photo %}
              <img src="{{ review.photo.url }}" class="img-thumbnail" alt="Фото отзыва">
            {% endif %}
            {% if request.user == review.user %}
                <a href="{% url 'main:edit_review' product.id review.id %}#review_form" class="btn btn-outline-primary btn-sm">Редактировать</a>
                <a href="{% url 'main:delete_review' review.id %}" class="btn btn-outline-danger btn-sm">Удалить</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

<script>
    function submitForm() {
        document.getElementById('colorFilterForm').submit();
    }
</script>



<script>
    document.addEventListener('DOMContentLoaded', function() {
        const radioButtons = document.querySelectorAll('input[type="radio"][name="color"]');
        const addToCartButton = document.getElementById('addToCartButton');
        const selectedColorInput = document.getElementById('selected_colorproduct');
    
        function updateButtonState() {
            // Поиск выбранной радио-кнопки
            const selectedRadio = Array.from(radioButtons).find(radio => radio.checked);
            
            // Установка значения скрытого поля в значение выбранной радио-кнопки
            if (selectedRadio) {
                selectedColorInput.value = selectedRadio.value;
                addToCartButton.disabled = false; // Активировать кнопку, если выбрана радио-кнопка
                addToCartButton.classList.remove('disabled');
            } else {
                selectedColorInput.value = ''; // Очистка, если нет выбранной радио-кнопки
                addToCartButton.disabled = true; // Деактивировать кнопку, если ничего не выбрано
                addToCartButton.classList.add('disabled');
            }
        }
    
        // Вешаем обработчик изменений на каждую радио-кнопку
        radioButtons.forEach(radio => radio.addEventListener('change', updateButtonState));
    
        // Инициализация состояния при загрузке страницы
        updateButtonState();
    });
    </script>
    
        
    

{% endblock %}